DROP TABLE IF EXISTS CAR;

CREATE TABLE CAR (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  CAR_NAME VARCHAR(50) NOT NULL,
  BRAND VARCHAR(50) NOT NULL,
  CATEGORY VARCHAR(50) DEFAULT 'No',
  RATING INT DEFAULT 0
);